### ISSUE TITLE
shouldScrollAtPage request

### ISSUE THREAD

**Issue by iPhoNewsRO** [uias/Pageboy#105]
hello, i am trying to only let the user scroll to the next pages if they fill some data in each page. i also want to only let them go back if they change their minds but they cannot continue until something is filled in the current page. how can i achieve this?

**Comment by haarismuneer** [comment]
You could set `isScrollEnabled` to false by default. Then you could check to see if all the data is filled in, and if it is, set `isScrollEnabled` to true.

**Comment by iPhoNewsRO** [comment]
yes, i'm already doing that. but that locks the scroll in both directions, i wanna lock only the scroll to right while scrolling to left to be functional

**Comment by msaps** [comment]
@iPhoNewsRO just had a quick look at if there was anything I could do in regards to direction locking, and unfortunately it looks like it won't be possible due to the weird stuff that `UIPageViewController` does with it's underlying `UIScrollView`.

It appears that `isDirectionLockEnabled` has no effect, and manually changing `contentOffset` doesn't work due to the VC reuse management from what I can tell.

**Comment by iPhoNewsRO** [comment]
thanks for the research, hopefully we could find something in the future
