### ISSUE TITLE
Using UIRefreshControl with PageboyPageViewController

### ISSUE THREAD

**Issue by mattbarker016** [uias/Pageboy#179]
Is there a way do add UIRefreshControl to activate on scrolling the `.first` view controller? I would love to be able to access the internal scrollView and add the UIRefreshControl to that. I understand why it's hidden though. Is there any other way I could implement this in the current system?

For more context, we're using a `.vertical` navigationOrientation.

**Comment by msaps** [comment]
@mattbarker016 unfortunately I would guess it wouldn't be possible. `UIPageVIewController` does some funky stuff to its internal `UIScrollView`, which is why this library exists probably 😄 - might be worth seeing if you can do it to a regular `UIPageViewController`, and if so then we can probably do something with Pageboy?

**Comment by mattbarker016** [comment]
We ended up moving our implementation back to a UIScrollView. Thanks, though!
