### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by RamblinWreck77** [uias/Pageboy#218]
Hello, I noticed the library defaults to Swift 4 when I run pod install/pod update. 

If I manually set swift 5 everything works fine, even shipped a few updates with this with zero issues. 

Is this a mistake or is there some reason to prefer swift 4 over 5?

**Comment by msaps** [comment]
@RamblinWreck77 because we want to support Swift 4 and 5 we unfortunately have to set the project/podspec Swift version to `4.0`. 

I believe with CocoaPods [1.7.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.rc.2) they are adding support for multiple supported swift versions to the pod spec - so as soon as that is available we will support it 👍
