### ISSUE TITLE
Even though scrollview is not scrolling isDragging method returns true

### ISSUE THREAD

**Issue by chamira** [uias/Pageboy#50]
I'm using Tabman lib, which is depended on Pageboy

**How to recreate**

_Select the last item, just try to do swipe gesture a couple of times to the left, then tap on the first item button. the scroll will not move._ 

When I debug I found, In below method it returns **true** even though the scroll is not visually moving.

PageboyViewController.swift
```
    /// Whether the page view controller is currently being dragged.
    public var isDragging: Bool {
        get {
            return self.pageViewController.scrollView?.isDragging ?? false
        }
    }
```

**Comment by msaps** [comment]
Thanks, I'll take a look at this and see what I can do 👍

**Comment by msaps** [comment]
@chamira I can't seem to be able to reproduce this, would you be able to provide a video showing the behaviour please?

**Comment by chamira** [comment]
Have you set self.bounces to false ??
Below is my setup in Child class of **TabmanViewController** .. hope it helps

```
        self.bounces = false
        self.bar.style = .buttonBar
        
        self.bar.appearance = TabmanBar.Appearance({ (appearance) in
            // customise appearance here            
            appearance.style.background = TabmanBarBackgroundView.BackgroundStyle.solid(color: UIColor.white)
            appearance.style.bottomSeparatorColor = UIColor(red: 220, green: 220, blue: 220)
            appearance.style.showEdgeFade = true
            
            appearance.layout.height = .explicit(value: 52)
            appearance.layout.interItemSpacing = 20.0
            appearance.layout.edgeInset  = 5
            
            appearance.state.color = UIColor.black
            appearance.state.selectedColor = UIColor.black
        
            appearance.indicator.lineWeight = TabmanIndicator.LineWeight.thick
            appearance.indicator.color = UIColor.red
            
        })
```

**Comment by msaps** [comment]
@chamira Thanks for all this, looks like a weird `UIPageViewController` / `UIScrollView` bug. Will take a look and review your PR. Cheers! 👍

**Comment by msaps** [comment]
@chamira had a bit of an investigation into the issue with the `isDragging` property.

Unfortunately, it seems as though the issue is a bit more severe than the state you've managed to reproduce. When attempting to scroll out of bounds with `.bounces` disabled there are issues with interaction on the scroll view itself being broken, as well as the `isDragging` property reporting incorrect values.

The `.bounces` property on Pageboy doesn't map directly to the `bounces` property on `UIScrollView` (As this doesn't work at all), instead using a workaround with setting `contentOffset`s on scroll events to create the same effect. Clearly the scroll view doesn't agree with this.

So unfortunately there isn't an easy fix to this, I'll have to take a good look at seeing if I can fix the `bounces` property functionality another way. 👎

**Comment by chamira** [comment]
👍
