### ISSUE TITLE
Func scrollToPage use for Tabman didSelectItemAtIndex will cause the screen to blink continuously

### ISSUE THREAD

**Issue by rockgarden** [uias/Pageboy#51]
In Tabman bar when user click Page No.5 from Page No.1, and use the func "scrollToPage(.at(index: index), animated: true)" will cause the screen to blink continuously.
This is caused by the setViewController animation.
But if I use scrollToPage(.at(index: index), animated: false) instead, the transition effect is low.
So I suggest optimize the scrollToPage for "func bar(_ bar: TabmanBar, didSelectItemAtIndex index: Int)" or add new func.
Maybe In page management only one scrollToPage func is not enough.

**Comment by msaps** [comment]
@rockgarden is this occurring in the Example project or in your own? If it's in the example project the flickering is due to the interpolation of the background gradients. The reason for the flickering could be  the same though...

When you scroll from index 0 (Page No. 1) to index 4 (Page No. 5), `Pageboy` will provide scroll updates across the whole range, i.e. 0.0 ... 1.0 ... 2.0 ... 3.0 ... 4.0, during the animation. Therefore in the example the gradients for each page are being interpolated between very quickly (as the animation speed is so fast). The behaviour is exactly what is desired, it just looks like flickering due to the speed.

If you are doing something similar with the page offset values, this might be the behaviour you are seeing?

**Comment by rockgarden** [comment]
Thank you for response, I get it.
I just hope in your Pageboy library can support Tabman bar click event, and don't Implemented by Pageboy scroll updates.

Now I just made a patch like below code :
func scrollToPage(_ pageIndex: PageIndex,
                             animated: Bool, pageAnimated: Bool = true,
                             completion: PageTransitionCompletion? = nil) {
            .....
            self.pageViewController.setViewControllers([viewController],
                                                       direction: direction.pageViewControllerNavDirection,
                                                       animated: pageAnimated,
                                                       completion:((Bool) -> Void)? = nil)
            ......

**Comment by msaps** [comment]
@rockgarden not sure I follow... 

The bar click event is handled internally and no action should be needed externally to complete the action, `scrollToPage()` is called automatically.
