### ISSUE TITLE
What about iOS 8 

### ISSUE THREAD

**Issue by farshadmb** [uias/Pageboy#75]
Hi Dear 
How you can support iOS 8

**Comment by msaps** [comment]
At the time I developed Pageboy I decided to support the current and the previous release of iOS (10 & 9), and I will probably leave the baseline at iOS 9 for the foreseeable future when adding support for iOS 11. 

I basically chose not to go down to iOS 8 due to the overhead/development effort, with the vast majority of the user base now being on iOS 10.

I don't think too much should be required to support iOS 8 API wise, so if you have a development environment set up for iOS 8, please do try adding support and submit a PR 👍

**Comment by msaps** [comment]
This is now available in [1.3.0](https://github.com/uias/Pageboy/releases/tag/1.3.0) 🎉
